
name: Deploy Frontend

on:
  workflow_run:
    workflows: ["Deploy Backend"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "connect4-frontend"
          heroku_email: "ingoandelhofs@gmail.com"
          appdir: "packages/frontend"